// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Questao5Web.DataContext;

#nullable disable

namespace Questao5Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240916000528_CreateBank")]
    partial class CreateBank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ContaCorrente", b =>
                {
                    b.Property<string>("IdContaCorrente")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdContaCorrente");

                    b.ToTable("ContaCorrentes");

                    b.HasData(
                        new
                        {
                            IdContaCorrente = "B6BAFC09-6967-ED11-A567-055DFA4A16C9",
                            Ativo = true,
                            Nome = "Katherine Sanchez",
                            Numero = 123
                        },
                        new
                        {
                            IdContaCorrente = "FA99D033-7067-ED11-96C6-7C5DFA4A16C9",
                            Ativo = true,
                            Nome = "Eva Woodward",
                            Numero = 456
                        },
                        new
                        {
                            IdContaCorrente = "382D323D-7067-ED11-8866-7D5DFA4A16C9",
                            Ativo = true,
                            Nome = "Tevin Mcconnell",
                            Numero = 789
                        },
                        new
                        {
                            IdContaCorrente = "F475F943-7067-ED11-A06B-7E5DFA4A16C9",
                            Ativo = false,
                            Nome = "Ameena Lynn",
                            Numero = 741
                        },
                        new
                        {
                            IdContaCorrente = "BCDACA4A-7067-ED11-AF81-825DFA4A16C9",
                            Ativo = false,
                            Nome = "Jarrad Mckee",
                            Numero = 852
                        },
                        new
                        {
                            IdContaCorrente = "D2E02051-7067-ED11-94C0-835DFA4A16C9",
                            Ativo = false,
                            Nome = "Elisha Simons",
                            Numero = 963
                        });
                });

            modelBuilder.Entity("Idempotencia", b =>
                {
                    b.Property<string>("ChaveIdempotencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requisicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChaveIdempotencia");

                    b.ToTable("Idempotencias");
                });

            modelBuilder.Entity("Movimento", b =>
                {
                    b.Property<string>("IdMovimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdContaCorrente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdContaCorrente");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("Movimento", b =>
                {
                    b.HasOne("ContaCorrente", "ContaCorrente")
                        .WithMany()
                        .HasForeignKey("IdContaCorrente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaCorrente");
                });
#pragma warning restore 612, 618
        }
    }
}
